version: 2

sources:
  - name: raw_data
    description: "Raw data sources for NYC taxi data"
    database: analytics-eng-with-bq-and-dbt # GCP project ID
    schema: nytaxi # Big Query dataset
    tables:
      - name: yellow_tripdata
      - name: green_tripdata